dataset:
  path: benchmark/datasets/longmemeval/longmemeval_s_reme_cleaned.json
  start_index: 0
  num_items: 500
  max_sessions: 0
  question_types: []
  workspace_root: benchmark/memory_workspaces/longmemeval-s
  question_ids:
  - b86304ba
  - 0862e8bf_abs
  - 19b5f2b3_abs
  - 29f2956b_abs
  - b5ef892d
  - aae3761f
  - c4a1ceb8
  - gpt4_2ba83207
  - gpt4_194be4b3
  - 5a7937c8
  - 10d9b85a
  - 60bf93ed_abs
  - edced276_abs
  - afdc33df
  - a89d7624
  - 1c0ddc50
  - 0a34ad58
  - 9aaed6a3
  - 7405e8b1
  - 5025383b
  - a1cc6108
  - b46e15ed
  - 9a707b81
  - gpt4_7f6b06db
  - gpt4_fa19884d
  - 0bc8ad93
  - gpt4_8279ba03
  - gpt4_2487a7cb
  - gpt4_76048e76
  - 0bb5a684
  - 2a1811e2
  - gpt4_5dcc0aab
  - gpt4_6ed717ea
  - gpt4_70e84552
  - 982b5123
  - gpt4_4edbafa2
  - gpt4_483dd43c
  - gpt4_b4a80587
  - gpt4_9a159967
  - 993da5e2
  - a3045048
  - gpt4_cd90e484
  - gpt4_1a1dc16d
  - gpt4_2f584639
  - 8c18457d
  - 982b5123_abs
  - 830ce83f
  - 184da446
  - 6a27ffc2
  - a2f3aa27
  - 0ddfec37_abs
  - f685340e_abs
evaluation:
  num_workers: 32
  filter_future_sessions: true
reme:
  config: lme.yaml
  dream_trigger_hour: 23
  dream_scan_days: 2
  dream_max_units: 5
output:
  dir: benchmark/results/longmemeval
  log_dir: logs
  log_prefix: longmemeval
  log_to_console: true
  log_to_file: true
